default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Fatima!6
  host: localhost
  pool: 5

development:
  <<: *default
  database: students_data_development

test:
  <<: *default
  database: students_data_test

production:
  <<: *default
  database: students_data_production
